/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ADM
 */
public class personalizarJogo extends javax.swing.JFrame {
    private String codigoAtual,disciplinaAtual,questaoAtual;
 private String altA,altB,altC,altD;
 private String novoCodigo, novaQuestao,novaDisciplina, novoAltA,novoAltB,novoAltC,novoAltD;
 private String consultaCodigos= " ";
 private String consultaDisciplina = " ";

    /**
     * Creates new form personalizarJogo
     */
    public personalizarJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultaCodigo = new javax.swing.JTextField();
        consultaDis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btConsult = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoQuestao = new javax.swing.JTextField();
        campoNovoCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoAltA = new javax.swing.JTextField();
        campoAltB = new javax.swing.JTextField();
        campoAltC = new javax.swing.JTextField();
        campoAltD = new javax.swing.JTextField();
        btConfirmarAlteracaoAluno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código do Jogo");

        consultaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaCodigoActionPerformed(evt);
            }
        });

        jLabel5.setText("Disciplina");

        btConsult.setText("consulta");
        btConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultActionPerformed(evt);
            }
        });

        jLabel4.setText("questão");

        jLabel8.setText("Novo Código do Jogo");

        jLabel2.setText("alternativa A");

        jLabel3.setText("alternativa B");

        jLabel6.setText("alternativa C");

        jLabel7.setText("alternativa D");

        campoAltC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAltCActionPerformed(evt);
            }
        });

        btConfirmarAlteracaoAluno.setText("confirmar");
        btConfirmarAlteracaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarAlteracaoAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(consultaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(consultaDis, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(campoNovoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoAltA, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel3)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(campoAltB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(campoAltC)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoAltD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btConsult)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btConfirmarAlteracaoAluno)
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultaDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btConsult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNovoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel8)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAltA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAltB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAltC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAltD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btConfirmarAlteracaoAluno)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaCodigoActionPerformed

    private void btConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultActionPerformed

        alterarJogo();

    }//GEN-LAST:event_btConsultActionPerformed

    private void campoAltCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAltCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAltCActionPerformed

    private void btConfirmarAlteracaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarAlteracaoAlunoActionPerformed

        confirmarAlteracao();
    }//GEN-LAST:event_btConfirmarAlteracaoAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmarAlteracaoAluno;
    private javax.swing.JButton btConsult;
    private javax.swing.JTextField campoAltA;
    private javax.swing.JTextField campoAltB;
    private javax.swing.JTextField campoAltC;
    private javax.swing.JTextField campoAltD;
    private javax.swing.JTextField campoNovoCodigo;
    private javax.swing.JTextField campoQuestao;
    private javax.swing.JTextField consultaCodigo;
    private javax.swing.JTextField consultaDis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public void alterarJogo()
 {
     
 

 int status;
				
				
	try
	{
               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
               Statement stm = con.createStatement();
               ResultSet res = stm.executeQuery("SELECT * from questoes");
					
                consultaCodigos = consultaCodigo.getText();
                consultaDisciplina = consultaDis.getText();
                status = 0;
		while(res.next())
		{
		   codigoAtual = res.getString("codigo");
                   disciplinaAtual = res.getString("disciplina");


		   
                   if(disciplinaAtual.compareTo(consultaDisciplina)==0 && codigoAtual.compareTo(consultaCodigos)==0)
		   {
			  questaoAtual = res.getString("questao");
                          altA= res.getString("a");
                          altB=res.getString("b");
                          altC=res.getString("c");
                          altD=res.getString("d");
			
			  status = 1;						  
		   }					   			   
		}
		if(status == 1)
		{
			campoQuestao.setText (questaoAtual);
			campoAltA.setText(altA);
                        campoAltB.setText(altB);
                        campoAltC.setText (altC);
                        campoAltD.setText(altD);
		}
		if(status == 0)
		{
			JOptionPane.showMessageDialog(null,"Nome: "+consultaCodigo+" n�o encontrado!!!","Erro",JOptionPane.ERROR_MESSAGE);
		}
	}
	catch(ClassNotFoundException ex)
	{
		JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
	}
	catch(SQLException ex)
	{
		JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
	}

 }
    
    public void confirmarAlteracao()
    {
         String classeDriver = "com.mysql.cj.jdbc.Driver";
	String stringConexao = "jdbc:mysql://localhost/aplicativo_educacional";
	String login = "root";
	String senha = "";
	Connection con;
	String sql;
        
        novoCodigo=campoNovoCodigo.getText();
        novaQuestao = campoQuestao.getText();  
        novaDisciplina = consultaDis.getText();
        novoAltA=campoAltA.getText();
        novoAltB=campoAltB.getText();
        novoAltC=campoAltC.getText();
        novoAltD=campoAltD.getText();
        
        
        
       con = null;
        
        sql = "SELECT *From questoaluno ";
        
        try
	{
	    Class.forName(classeDriver);
	    con = DriverManager.getConnection(stringConexao, login, senha);
	    PreparedStatement stmt = con.prepareStatement(sql);
           

	    /*int x=stmt.executeUpdate("UPDATE questoes SET codigo='"+novoCodigo+"'," +
	         "disciplina='"+disciplinaAtual+"',questao='"+novaQuestao
                    +"', a='"+novoAltA+"', b='"+novoAltB+"', c='"+novoAltC+"', d='"+novoAltD+"' WHERE codigo="+consultaCodigos);*/
            
            int x=stmt.executeUpdate("UPDATE questoes SET disciplina='"+disciplinaAtual+"',questao='"+novaQuestao
                    +"', a='"+novoAltA+"', b='"+novoAltB+"', c='"+novoAltC+"', d='"+novoAltD+"' WHERE codigo="+consultaCodigos);
            
            if (x == 1 )
                JOptionPane.showMessageDialog(null,"Jogo atualizado com sucesso!","",JOptionPane.INFORMATION_MESSAGE);
        }
	catch(SQLException ex)
	{
	   JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.INFORMATION_MESSAGE);
	}
	catch(ClassNotFoundException ex)
	{
	   JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.INFORMATION_MESSAGE);
	}
 
    }

}
