/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;

/**
 *
 * @author fellr
 */
public class LgPtDois extends javax.swing.JFrame {
    private LgPtTres TelaLgPtTres;

    /**
     * Creates new form LgPtDois
     */
    public LgPtDois() {
        initComponents();
        TelaLgPtTres = new LgPtTres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLgPtDois = new javax.swing.JPanel();
        jlLgPtDoisA = new javax.swing.JLabel();
        jlLgPtDoisB = new javax.swing.JLabel();
        btLgPtDoisA = new javax.swing.JButton();
        btLgPtDoisB = new javax.swing.JButton();
        btLgPtDoisC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlLgPtDoisA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlLgPtDoisA.setText("Qual é a forma que possui ");

        jlLgPtDoisB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlLgPtDoisB.setText("quatro lados iguais?");

        btLgPtDoisA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btLgPtDoisB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btLgPtDoisB.setText("Aqui");
        btLgPtDoisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLgPtDoisBActionPerformed(evt);
            }
        });

        btLgPtDoisC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout PainelLgPtDoisLayout = new javax.swing.GroupLayout(PainelLgPtDois);
        PainelLgPtDois.setLayout(PainelLgPtDoisLayout);
        PainelLgPtDoisLayout.setHorizontalGroup(
            PainelLgPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLgPtDoisLayout.createSequentialGroup()
                .addGroup(PainelLgPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLgPtDoisLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jlLgPtDoisB))
                    .addGroup(PainelLgPtDoisLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jlLgPtDoisA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLgPtDoisLayout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addGroup(PainelLgPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLgPtDoisLayout.createSequentialGroup()
                        .addComponent(btLgPtDoisA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btLgPtDoisC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLgPtDoisLayout.createSequentialGroup()
                        .addComponent(btLgPtDoisB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))))
        );
        PainelLgPtDoisLayout.setVerticalGroup(
            PainelLgPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLgPtDoisLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlLgPtDoisA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlLgPtDoisB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(PainelLgPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLgPtDoisA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLgPtDoisC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btLgPtDoisB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelLgPtDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelLgPtDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLgPtDoisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLgPtDoisBActionPerformed
      TelaLgPtTres.setVisible(true);
      dispose();
    }//GEN-LAST:event_btLgPtDoisBActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelLgPtDois;
    private javax.swing.JButton btLgPtDoisA;
    private javax.swing.JButton btLgPtDoisB;
    private javax.swing.JButton btLgPtDoisC;
    private javax.swing.JLabel jlLgPtDoisA;
    private javax.swing.JLabel jlLgPtDoisB;
    // End of variables declaration//GEN-END:variables
}
