/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;
import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;
/**
 *
 * @author ADM
 */
public class MtCinco extends javax.swing.JFrame {
    MtSeis TelaMtSeis;
    int pontosMt = PontosAluno.getPontosMt();
     int idAluno=0;
    /**
     * Creates new form MtCinco
     */
    public MtCinco() {
        initComponents();
        TelaMtSeis = new MtSeis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMtCinco = new javax.swing.JPanel();
        jlMtCinco = new javax.swing.JLabel();
        btMtCincoA = new javax.swing.JButton();
        btMtCincoB = new javax.swing.JButton();
        btMtCincoC = new javax.swing.JButton();
        btMtCincoD = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();
        btVoltarMt = new javax.swing.JButton();
        btPtDica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 420));

        PainelMtCinco.setPreferredSize(new java.awt.Dimension(700, 400));
        PainelMtCinco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMtCinco.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MtCinco.png"))); // NOI18N
        PainelMtCinco.add(jlMtCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btMtCincoA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtCincoA.setText("21");
        btMtCincoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtCincoAActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btMtCincoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 143, 190, 80));

        btMtCincoB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtCincoB.setText("12");
        btMtCincoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtCincoBActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btMtCincoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 134, 180, 90));

        btMtCincoC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtCincoC.setText("8");
        btMtCincoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtCincoCActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btMtCincoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 255, 190, 90));

        btMtCincoD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtCincoD.setText("7");
        btMtCincoD.setPreferredSize(new java.awt.Dimension(700, 420));
        btMtCincoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtCincoDActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btMtCincoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 255, 180, 90));

        btVoltarMenu.setText(" MENU");
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btVoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 80, 40));

        btAvancar.setText("Avançar");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 344, 90, 50));

        btVoltarMt.setText("Voltar");
        btVoltarMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMtActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btVoltarMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 354, 80, 40));

        btPtDica.setText("?");
        btPtDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtDicaActionPerformed(evt);
            }
        });
        PainelMtCinco.add(btPtDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 6, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMtCincoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtCincoAActionPerformed
     pontosMt=pontosMt-5;     // TODO add your handling code here:
    }//GEN-LAST:event_btMtCincoAActionPerformed

    private void btMtCincoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtCincoBActionPerformed
    pontosMt=pontosMt-5;      // TODO add your handling code here:
    }//GEN-LAST:event_btMtCincoBActionPerformed

    private void btMtCincoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtCincoCActionPerformed
      pontosMt=pontosMt-5;    // TODO add your handling code here:
    }//GEN-LAST:event_btMtCincoCActionPerformed

    private void btMtCincoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtCincoDActionPerformed
      pontosMt=pontosMt+20;
        System.out.println(""+pontosMt);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                 
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q5="+pontosMt+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }   
        TelaMtSeis.setVisible(true);
        dispose();
    }//GEN-LAST:event_btMtCincoDActionPerformed

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        TelaMtSeis.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed
        new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btVoltarMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMtActionPerformed
        new MtQuatro ().show();
        dispose();
    }//GEN-LAST:event_btVoltarMtActionPerformed

    private void btPtDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtDicaActionPerformed
        JOptionPane.showMessageDialog(null,"Uma dica é voce tentar gritar a palavra em sua cabeça, a silaba que tiver mais ênfase é a sílaba tónica, exemplo: Abacaxiiii!");
    }//GEN-LAST:event_btPtDicaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMtCinco;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btMtCincoA;
    private javax.swing.JButton btMtCincoB;
    private javax.swing.JButton btMtCincoC;
    private javax.swing.JButton btMtCincoD;
    private javax.swing.JButton btPtDica;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JButton btVoltarMt;
    private javax.swing.JLabel jlMtCinco;
    // End of variables declaration//GEN-END:variables
}
