/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;
import telas.menuPrincipal;

/**
 *
 * @author ADM
 */
public class MtDez extends javax.swing.JFrame {

    /**
     * Creates new form MtDez
     */
    public MtDez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMtDez = new javax.swing.JPanel();
        jlMtDezA = new javax.swing.JLabel();
        btMtDezA = new javax.swing.JButton();
        btMtDezB = new javax.swing.JButton();
        btMtDezC = new javax.swing.JButton();
        btMtDezD = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlMtDezA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtDezA.setText("Qual número abaixo é Ímpar?");

        btMtDezA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtDezA.setText("2");
        btMtDezA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtDezAActionPerformed(evt);
            }
        });

        btMtDezB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtDezB.setText("6");
        btMtDezB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtDezBActionPerformed(evt);
            }
        });

        btMtDezC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtDezC.setText("5");
        btMtDezC.setPreferredSize(new java.awt.Dimension(700, 420));
        btMtDezC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtDezCActionPerformed(evt);
            }
        });

        btMtDezD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtDezD.setText("8");
        btMtDezD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtDezDActionPerformed(evt);
            }
        });

        btAvancar.setText("Avançar");

        btVoltarMenu.setText("Voltar para o MENU");

        javax.swing.GroupLayout PainelMtDezLayout = new javax.swing.GroupLayout(PainelMtDez);
        PainelMtDez.setLayout(PainelMtDezLayout);
        PainelMtDezLayout.setHorizontalGroup(
            PainelMtDezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMtDezLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltarMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtDezLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PainelMtDezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtDezLayout.createSequentialGroup()
                        .addGroup(PainelMtDezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMtDezA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMtDezC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(PainelMtDezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMtDezD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMtDezB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtDezLayout.createSequentialGroup()
                        .addComponent(btAvancar)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtDezLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jlMtDezA)
                .addGap(105, 105, 105))
        );
        PainelMtDezLayout.setVerticalGroup(
            PainelMtDezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMtDezLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jlMtDezA)
                .addGap(31, 31, 31)
                .addGroup(PainelMtDezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMtDezA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMtDezB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelMtDezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMtDezD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMtDezC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btAvancar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PainelMtDez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtDez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMtDezAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtDezAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMtDezAActionPerformed

    private void btMtDezBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtDezBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMtDezBActionPerformed

    private void btMtDezCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtDezCActionPerformed
        new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btMtDezCActionPerformed

    private void btMtDezDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtDezDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMtDezDActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMtDez;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btMtDezA;
    private javax.swing.JButton btMtDezB;
    private javax.swing.JButton btMtDezC;
    private javax.swing.JButton btMtDezD;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JLabel jlMtDezA;
    // End of variables declaration//GEN-END:variables
}
