/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;
import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;

/**
 *
 * @author ADM
 */
public class MtOito extends javax.swing.JFrame {
  private MtNove TelaMtNove;
   int pontosMt = PontosAluno.getPontosMt();
     int idAluno=0;
    /**
     *
     * Creates new form MtOito
     */
    public MtOito() {
        initComponents();
        TelaMtNove = new MtNove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMtOito = new javax.swing.JPanel();
        jlMtOito = new javax.swing.JLabel();
        btMtOitoA = new javax.swing.JButton();
        btMtOitoB = new javax.swing.JButton();
        btMtOitoC = new javax.swing.JButton();
        btMtOitoD = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        btVoltarMt = new javax.swing.JButton();
        btPtDica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelMtOito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMtOito.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtOito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MtOito.png"))); // NOI18N
        PainelMtOito.add(jlMtOito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btMtOitoA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtOitoA.setText("8");
        btMtOitoA.setPreferredSize(new java.awt.Dimension(700, 420));
        btMtOitoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtOitoAActionPerformed(evt);
            }
        });
        PainelMtOito.add(btMtOitoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 141, 180, 80));

        btMtOitoB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtOitoB.setText("6");
        btMtOitoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtOitoBActionPerformed(evt);
            }
        });
        PainelMtOito.add(btMtOitoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 141, 180, 80));

        btMtOitoC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtOitoC.setText("10");
        btMtOitoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtOitoCActionPerformed(evt);
            }
        });
        PainelMtOito.add(btMtOitoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 263, 180, 80));

        btMtOitoD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtOitoD.setText("7");
        btMtOitoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtOitoDActionPerformed(evt);
            }
        });
        PainelMtOito.add(btMtOitoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 263, 180, 80));

        btAvancar.setText("Avançar");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });
        PainelMtOito.add(btAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 344, 90, 50));

        btVoltarMenu.setText("MENU");
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });
        PainelMtOito.add(btVoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 80, 40));

        btVoltarMt.setText("Voltar");
        btVoltarMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMtActionPerformed(evt);
            }
        });
        PainelMtOito.add(btVoltarMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 371, -1, -1));

        btPtDica.setText("?");
        btPtDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtDicaActionPerformed(evt);
            }
        });
        PainelMtOito.add(btPtDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 6, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtOito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtOito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMtOitoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtOitoAActionPerformed
       pontosMt=pontosMt+20;
        System.out.println(""+pontosMt);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                 
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q8="+pontosMt+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }   
        TelaMtNove.setVisible(true);
       dispose();
    }//GEN-LAST:event_btMtOitoAActionPerformed

    private void btMtOitoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtOitoBActionPerformed
    pontosMt=pontosMt-5;    // TODO add your handling code here:
    }//GEN-LAST:event_btMtOitoBActionPerformed

    private void btMtOitoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtOitoCActionPerformed
      pontosMt=pontosMt-5;  // TODO add your handling code here:
    }//GEN-LAST:event_btMtOitoCActionPerformed

    private void btMtOitoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtOitoDActionPerformed
      pontosMt=pontosMt-5;  // TODO add your handling code here:
    }//GEN-LAST:event_btMtOitoDActionPerformed

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        TelaMtNove.setVisible(true);
       dispose();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed
         new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btVoltarMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMtActionPerformed
        new MtSete().show();
        dispose();
    }//GEN-LAST:event_btVoltarMtActionPerformed

    private void btPtDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtDicaActionPerformed
        JOptionPane.showMessageDialog(null,"Uma dica é voce tentar gritar a palavra em sua cabeça, a silaba que tiver mais ênfase é a sílaba tónica, exemplo: Abacaxiiii!");
    }//GEN-LAST:event_btPtDicaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMtOito;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btMtOitoA;
    private javax.swing.JButton btMtOitoB;
    private javax.swing.JButton btMtOitoC;
    private javax.swing.JButton btMtOitoD;
    private javax.swing.JButton btPtDica;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JButton btVoltarMt;
    private javax.swing.JLabel jlMtOito;
    // End of variables declaration//GEN-END:variables
}
