/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;
import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;
/**
 *
 * @author ADM
 */
public class MtQuatro extends javax.swing.JFrame {
 private MtCinco TelaMtCinco;
 int pontosMt = PontosAluno.getPontosMt();
     int idAluno=0;
    /**
     * Creates new form MtQuatro
     */
    public MtQuatro() {
        initComponents();
        TelaMtCinco = new MtCinco ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMtQuatro = new javax.swing.JPanel();
        jlMtQuatroA = new javax.swing.JLabel();
        jlMtQuatroB = new javax.swing.JLabel();
        btMtQuatroA = new javax.swing.JButton();
        btMtQuatroC = new javax.swing.JButton();
        btMtQuatroD = new javax.swing.JButton();
        btMtQuatroB = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        btVoltarMt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelMtQuatro.setPreferredSize(new java.awt.Dimension(700, 420));

        jlMtQuatroA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtQuatroA.setText("Qual o valor da operação");

        jlMtQuatroB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtQuatroB.setText("\"8 - 5\"?");

        btMtQuatroA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtQuatroA.setText("3");
        btMtQuatroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtQuatroAActionPerformed(evt);
            }
        });

        btMtQuatroC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtQuatroC.setText("4");
        btMtQuatroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtQuatroCActionPerformed(evt);
            }
        });

        btMtQuatroD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtQuatroD.setText("7");
        btMtQuatroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtQuatroDActionPerformed(evt);
            }
        });

        btMtQuatroB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtQuatroB.setText("13");
        btMtQuatroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtQuatroBActionPerformed(evt);
            }
        });

        btAvancar.setText("Avançar");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });

        btVoltarMenu.setText(" MENU");
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });

        btVoltarMt.setText("Voltar");
        btVoltarMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMtQuatroLayout = new javax.swing.GroupLayout(PainelMtQuatro);
        PainelMtQuatro.setLayout(PainelMtQuatroLayout);
        PainelMtQuatroLayout.setHorizontalGroup(
            PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMtQuatroLayout.createSequentialGroup()
                .addComponent(btVoltarMenu)
                .addContainerGap(637, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                        .addComponent(btVoltarMt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMtQuatroA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMtQuatroC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelMtQuatroLayout.createSequentialGroup()
                                .addComponent(btMtQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(PainelMtQuatroLayout.createSequentialGroup()
                                .addComponent(btMtQuatroD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAvancar)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                                .addComponent(jlMtQuatroB)
                                .addGap(294, 294, 294))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                                .addComponent(jlMtQuatroA)
                                .addGap(135, 135, 135))))))
        );
        PainelMtQuatroLayout.setVerticalGroup(
            PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMtQuatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlMtQuatroA)
                .addGap(18, 18, 18)
                .addComponent(jlMtQuatroB)
                .addGap(18, 18, 18)
                .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMtQuatroA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMtQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelMtQuatroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btMtQuatroC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMtQuatroD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelMtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                                .addComponent(btAvancar)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtQuatroLayout.createSequentialGroup()
                                .addComponent(btVoltarMt)
                                .addGap(39, 39, 39))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMtQuatroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtQuatroAActionPerformed
      pontosMt=pontosMt+20;
        System.out.println(""+pontosMt);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                 
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q4="+pontosMt+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }     
        TelaMtCinco.setVisible(true);
         dispose();
    }//GEN-LAST:event_btMtQuatroAActionPerformed

    private void btMtQuatroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtQuatroCActionPerformed
   pontosMt=pontosMt-5;       // TODO add your handling code here:
    }//GEN-LAST:event_btMtQuatroCActionPerformed

    private void btMtQuatroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtQuatroDActionPerformed
  pontosMt=pontosMt-5;  
    }//GEN-LAST:event_btMtQuatroDActionPerformed

    private void btMtQuatroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtQuatroBActionPerformed
     pontosMt=pontosMt-5;     // TODO add your handling code here:
    }//GEN-LAST:event_btMtQuatroBActionPerformed

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        TelaMtCinco.setVisible(true);
         dispose();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed
         new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btVoltarMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMtActionPerformed
        new MtTres ().show();
        dispose();
    }//GEN-LAST:event_btVoltarMtActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMtQuatro;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btMtQuatroA;
    private javax.swing.JButton btMtQuatroB;
    private javax.swing.JButton btMtQuatroC;
    private javax.swing.JButton btMtQuatroD;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JButton btVoltarMt;
    private javax.swing.JLabel jlMtQuatroA;
    private javax.swing.JLabel jlMtQuatroB;
    // End of variables declaration//GEN-END:variables
}
