/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;
import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;

/**
 *
 * @author ADM
 */
public class MtSeis extends javax.swing.JFrame {
  private MtSete TelaMtSete;
  int pontosMt = PontosAluno.getPontosMt();
     int idAluno=0;
    /**
     * Creates new form MtSeis
     */
    public MtSeis() {
        initComponents();
        TelaMtSete = new MtSete ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMtSeis = new javax.swing.JPanel();
        jlMtSeisA = new javax.swing.JLabel();
        btMtSeisA = new javax.swing.JButton();
        btMtSeisB = new javax.swing.JButton();
        btMtSeisC = new javax.swing.JButton();
        btMtSeisD = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        btVoltarMt = new javax.swing.JButton();
        btPtDica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelMtSeis.setPreferredSize(new java.awt.Dimension(700, 400));
        PainelMtSeis.setRequestFocusEnabled(false);
        PainelMtSeis.setVerifyInputWhenFocusTarget(false);
        PainelMtSeis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMtSeisA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtSeisA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MtSeis.png"))); // NOI18N
        jlMtSeisA.setText("15");
        PainelMtSeis.add(jlMtSeisA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        btMtSeisA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtSeisA.setText("15");
        btMtSeisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtSeisAActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btMtSeisA, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 135, 190, 90));

        btMtSeisB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtSeisB.setText("5");
        btMtSeisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtSeisBActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btMtSeisB, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 135, 190, 90));

        btMtSeisC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtSeisC.setText("9");
        btMtSeisC.setPreferredSize(new java.awt.Dimension(700, 420));
        btMtSeisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtSeisCActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btMtSeisC, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 255, 190, 90));

        btMtSeisD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtSeisD.setText("10");
        btMtSeisD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtSeisDActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btMtSeisD, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 255, 180, 90));

        btAvancar.setText("Avançar");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 345, 90, 50));

        btVoltarMenu.setText(" MENU");
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btVoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 40));

        btVoltarMt.setText("Voltar");
        btVoltarMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMtActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btVoltarMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 345, 80, 50));

        btPtDica.setText("?");
        btPtDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtDicaActionPerformed(evt);
            }
        });
        PainelMtSeis.add(btPtDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 6, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMtSeisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtSeisAActionPerformed
      pontosMt=pontosMt-5;    // TODO add your handling code here:
    }//GEN-LAST:event_btMtSeisAActionPerformed

    private void btMtSeisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtSeisBActionPerformed
     pontosMt=pontosMt-5;     // TODO add your handling code here:
    }//GEN-LAST:event_btMtSeisBActionPerformed

    private void btMtSeisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtSeisCActionPerformed
       pontosMt=pontosMt+20;
        System.out.println(""+pontosMt);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                 
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q6="+pontosMt+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }   
        TelaMtSete.setVisible(true);
        dispose();
    }//GEN-LAST:event_btMtSeisCActionPerformed

    private void btMtSeisDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtSeisDActionPerformed
      pontosMt=pontosMt-5;    // TODO add your handling code here:
    }//GEN-LAST:event_btMtSeisDActionPerformed

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
         TelaMtSete.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed
        new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btVoltarMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMtActionPerformed
        new MtCinco ().show();
        dispose();
    }//GEN-LAST:event_btVoltarMtActionPerformed

    private void btPtDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtDicaActionPerformed
        JOptionPane.showMessageDialog(null,"A operação é subtração ou seja, se você tem 5 laranjas e deu 2, você tem 3 laranjas agora!");
    }//GEN-LAST:event_btPtDicaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMtSeis;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btMtSeisA;
    private javax.swing.JButton btMtSeisB;
    private javax.swing.JButton btMtSeisC;
    private javax.swing.JButton btMtSeisD;
    private javax.swing.JButton btPtDica;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JButton btVoltarMt;
    private javax.swing.JLabel jlMtSeisA;
    // End of variables declaration//GEN-END:variables
}
