/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;
import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;
/**
 *
 * @author ADM
 */
public class MtTres extends javax.swing.JFrame {
  private MtQuatro  TelaMtQuatro;
  int pontosMt = PontosAluno.getPontosMt();
     int idAluno=0;
    /**
     * Creates new form MtTres
     */
    public MtTres() {
        initComponents();
        TelaMtQuatro = new MtQuatro ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMtTres = new javax.swing.JPanel();
        jlMtTresA = new javax.swing.JLabel();
        jlMtTresB = new javax.swing.JLabel();
        btMtTresA = new javax.swing.JButton();
        btMtTresB = new javax.swing.JButton();
        btMtTresC = new javax.swing.JButton();
        btMtTresD = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        btVoltarMt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelMtTres.setPreferredSize(new java.awt.Dimension(700, 420));

        jlMtTresA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtTresA.setText("Qual o valor da operação");

        jlMtTresB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlMtTresB.setText("\"9 + 9\"");

        btMtTresA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtTresA.setText("20");
        btMtTresA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtTresAActionPerformed(evt);
            }
        });

        btMtTresB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtTresB.setText("0");
        btMtTresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtTresBActionPerformed(evt);
            }
        });

        btMtTresC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtTresC.setText("18");
        btMtTresC.setPreferredSize(new java.awt.Dimension(700, 420));
        btMtTresC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtTresCActionPerformed(evt);
            }
        });

        btMtTresD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMtTresD.setText("16");
        btMtTresD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMtTresDActionPerformed(evt);
            }
        });

        btAvancar.setText("Avançar");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });

        btVoltarMenu.setText("MENU");
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });

        btVoltarMt.setText("Voltar");
        btVoltarMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMtTresLayout = new javax.swing.GroupLayout(PainelMtTres);
        PainelMtTres.setLayout(PainelMtTresLayout);
        PainelMtTresLayout.setHorizontalGroup(
            PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMtTresLayout.createSequentialGroup()
                .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelMtTresLayout.createSequentialGroup()
                        .addComponent(btVoltarMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtTresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btVoltarMt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMtTresA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMtTresC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMtTresD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMtTresB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)))
                .addComponent(btAvancar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtTresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtTresLayout.createSequentialGroup()
                        .addComponent(jlMtTresB)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtTresLayout.createSequentialGroup()
                        .addComponent(jlMtTresA)
                        .addGap(148, 148, 148))))
        );
        PainelMtTresLayout.setVerticalGroup(
            PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMtTresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltarMenu)
                .addGap(21, 21, 21)
                .addComponent(jlMtTresA)
                .addGap(18, 18, 18)
                .addComponent(jlMtTresB)
                .addGap(18, 18, 18)
                .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMtTresA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMtTresB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelMtTresLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btMtTresC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMtTresD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtTresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelMtTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtTresLayout.createSequentialGroup()
                                .addComponent(btAvancar)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMtTresLayout.createSequentialGroup()
                                .addComponent(btVoltarMt)
                                .addGap(25, 25, 25))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMtTres, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMtTresAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtTresAActionPerformed
    pontosMt=pontosMt-5;     // TODO add your handling code here:
    }//GEN-LAST:event_btMtTresAActionPerformed

    private void btMtTresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtTresBActionPerformed
     pontosMt=pontosMt-5;    // TODO add your handling code here:
    }//GEN-LAST:event_btMtTresBActionPerformed

    private void btMtTresCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtTresCActionPerformed
      pontosMt=pontosMt+20;
        System.out.println(""+pontosMt);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                 
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q3="+pontosMt+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }   
        
        TelaMtQuatro.setVisible(true);
       dispose();
    }//GEN-LAST:event_btMtTresCActionPerformed

    private void btMtTresDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMtTresDActionPerformed
    pontosMt=pontosMt-5;     // TODO add your handling code here:
    }//GEN-LAST:event_btMtTresDActionPerformed

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        TelaMtQuatro.setVisible(true);
       dispose();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed
         new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btVoltarMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMtActionPerformed
        new MtDois ().show();
        dispose();
    }//GEN-LAST:event_btVoltarMtActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMtTres;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btMtTresA;
    private javax.swing.JButton btMtTresB;
    private javax.swing.JButton btMtTresC;
    private javax.swing.JButton btMtTresD;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JButton btVoltarMt;
    private javax.swing.JLabel jlMtTresA;
    private javax.swing.JLabel jlMtTresB;
    // End of variables declaration//GEN-END:variables
}
