/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;

/**
 *
 * @author aluno
 */
public class PtDois extends javax.swing.JFrame {
     private PtTres TelaPtTres;
    /**
     * Creates new form PtDois
     */
    public PtDois() {
        initComponents();
        TelaPtTres = new PtTres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPtDois = new javax.swing.JPanel();
        jlPtUmA = new javax.swing.JLabel();
        btPtDoisA = new javax.swing.JButton();
        btPtDoisB = new javax.swing.JButton();
        btPtDoisC = new javax.swing.JButton();
        btPtDoisD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 420));
        setResizable(false);

        jlPtUmA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlPtUmA.setText("Qual é o plural da palavra \"CACHORRO\"?");

        btPtDoisA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtDoisA.setText("CACHORRUZ");

        btPtDoisB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtDoisB.setText("CACHORROZ");

        btPtDoisC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtDoisC.setText("CACHORROS");
        btPtDoisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtDoisCActionPerformed(evt);
            }
        });

        btPtDoisD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtDoisD.setText("CACHORRES");

        javax.swing.GroupLayout PainelPtDoisLayout = new javax.swing.GroupLayout(PainelPtDois);
        PainelPtDois.setLayout(PainelPtDoisLayout);
        PainelPtDoisLayout.setHorizontalGroup(
            PainelPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPtDoisLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(PainelPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelPtDoisLayout.createSequentialGroup()
                        .addComponent(btPtDoisA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPtDoisB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPtDoisLayout.createSequentialGroup()
                        .addComponent(btPtDoisC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btPtDoisD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPtDoisLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jlPtUmA, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        PainelPtDoisLayout.setVerticalGroup(
            PainelPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPtDoisLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jlPtUmA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(PainelPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPtDoisA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPtDoisB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelPtDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPtDoisC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPtDoisD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jlPtUmA.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPtDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPtDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPtDoisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtDoisCActionPerformed
      TelaPtTres.setVisible(true);
      dispose();
    }//GEN-LAST:event_btPtDoisCActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPtDois;
    private javax.swing.JButton btPtDoisA;
    private javax.swing.JButton btPtDoisB;
    private javax.swing.JButton btPtDoisC;
    private javax.swing.JButton btPtDoisD;
    private javax.swing.JLabel jlPtUmA;
    // End of variables declaration//GEN-END:variables
}
