/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;
import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;

/**
 *
 * @author aluno
 */
public class PtQuatro extends javax.swing.JFrame {
    private PtCinco TelaPtCinco;
    int pontosPt = PontosAluno.getPontosPt();
      int idAluno=0;
    /**
     * Creates new form PtQuatro
     */
    public PtQuatro() {
        initComponents();
        TelaPtCinco = new PtCinco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelPtQuatro = new javax.swing.JPanel();
        jlPtQuatroA = new javax.swing.JLabel();
        jlPtQuatroB = new javax.swing.JLabel();
        btPtQuatroA = new javax.swing.JButton();
        btPtQuatroB = new javax.swing.JButton();
        btPtQuatroC = new javax.swing.JButton();
        btPtQuatroD = new javax.swing.JButton();
        btPtVM = new javax.swing.JButton();
        btPtDica = new javax.swing.JButton();
        btPtAvancar = new javax.swing.JButton();
        btVoltarPt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPtQuatro.setPreferredSize(new java.awt.Dimension(700, 400));
        PainelPtQuatro.setRequestFocusEnabled(false);
        PainelPtQuatro.setVerifyInputWhenFocusTarget(false);

        jlPtQuatroA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlPtQuatroA.setText("Qual é a palavra que tem o");

        jlPtQuatroB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlPtQuatroB.setText("mesmo significado que \"BONITO\"?");

        btPtQuatroA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtQuatroA.setText("GRANDE ");
        btPtQuatroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtQuatroAActionPerformed(evt);
            }
        });

        btPtQuatroB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtQuatroB.setText("BELO");
        btPtQuatroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtQuatroBActionPerformed(evt);
            }
        });

        btPtQuatroC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtQuatroC.setText("PEQUENINO");
        btPtQuatroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtQuatroCActionPerformed(evt);
            }
        });

        btPtQuatroD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtQuatroD.setText("NORMAL");
        btPtQuatroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtQuatroDActionPerformed(evt);
            }
        });

        btPtVM.setText("MENU");
        btPtVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtVMActionPerformed(evt);
            }
        });

        btPtDica.setText("?");
        btPtDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtDicaActionPerformed(evt);
            }
        });

        btPtAvancar.setText("Avançar");
        btPtAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtAvancarActionPerformed(evt);
            }
        });

        btVoltarPt.setText("Voltar");
        btVoltarPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarPtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPtQuatroLayout = new javax.swing.GroupLayout(PainelPtQuatro);
        PainelPtQuatro.setLayout(PainelPtQuatroLayout);
        PainelPtQuatroLayout.setHorizontalGroup(
            PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPtQuatroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btPtVM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPtDica)
                .addGap(17, 17, 17))
            .addGroup(PainelPtQuatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltarPt)
                .addGap(57, 57, 57)
                .addGroup(PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPtQuatroLayout.createSequentialGroup()
                        .addGroup(PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPtQuatroC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPtQuatroA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPtQuatroD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPtQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlPtQuatroA))
                .addGap(29, 29, 29)
                .addComponent(btPtAvancar)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPtQuatroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPtQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        PainelPtQuatroLayout.setVerticalGroup(
            PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPtQuatroLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPtVM)
                    .addComponent(btPtDica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPtQuatroA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlPtQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelPtQuatroLayout.createSequentialGroup()
                        .addGroup(PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btPtQuatroA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPtQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PainelPtQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPtQuatroD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPtQuatroC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btPtAvancar)
                    .addComponent(btVoltarPt))
                .addGap(40, 40, 40))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(PainelPtQuatro, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPtQuatroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtQuatroCActionPerformed
pontosPt=pontosPt-5;        // TODO add your handling code here:
    }//GEN-LAST:event_btPtQuatroCActionPerformed

    private void btPtQuatroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtQuatroBActionPerformed
       pontosPt=pontosPt+20;
        System.out.println(""+pontosPt);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
             ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q4="+pontosPt+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }   
        
        TelaPtCinco.setVisible(true);
      dispose();
    }//GEN-LAST:event_btPtQuatroBActionPerformed

    private void btPtVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtVMActionPerformed
        new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btPtVMActionPerformed

    private void btPtDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtDicaActionPerformed
        JOptionPane.showMessageDialog(null,"Algo idêntico ou semelhante, exemplo: o semelhante de ruim é mal");
    }//GEN-LAST:event_btPtDicaActionPerformed

    private void btPtAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtAvancarActionPerformed
          pontosPt=0;
        System.out.println(""+pontosPt);
        TelaPtCinco.setVisible(true);
        dispose();
    }//GEN-LAST:event_btPtAvancarActionPerformed

    private void btPtQuatroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtQuatroAActionPerformed
pontosPt=pontosPt-5;        // TODO add your handling code here:
    }//GEN-LAST:event_btPtQuatroAActionPerformed

    private void btPtQuatroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtQuatroDActionPerformed
pontosPt=pontosPt-5;        // TODO add your handling code here:
    }//GEN-LAST:event_btPtQuatroDActionPerformed

    private void btVoltarPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarPtActionPerformed
        new PtTres ().show();
        dispose();
    }//GEN-LAST:event_btVoltarPtActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPtQuatro;
    private javax.swing.JButton btPtAvancar;
    private javax.swing.JButton btPtDica;
    private javax.swing.JButton btPtQuatroA;
    private javax.swing.JButton btPtQuatroB;
    private javax.swing.JButton btPtQuatroC;
    private javax.swing.JButton btPtQuatroD;
    private javax.swing.JButton btPtVM;
    private javax.swing.JButton btVoltarPt;
    private javax.swing.JLabel jlPtQuatroA;
    private javax.swing.JLabel jlPtQuatroB;
    // End of variables declaration//GEN-END:variables
}
