/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;
import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;

/**
 *
 * @author aluno
 */
public class PtUm extends javax.swing.JFrame {
    private PtDois TelaPtDois;
     int pontosPt = PontosAluno.getPontosPt();
     String tipo="portugues";

    /**
     * Creates new form PtUm
     */
    public PtUm() {
        initComponents();
        TelaPtDois = new PtDois();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelPtUm = new javax.swing.JPanel();
        jlPtUmA = new javax.swing.JLabel();
        jlPtUmB = new javax.swing.JLabel();
        btPtUmA = new javax.swing.JButton();
        btPtUmB = new javax.swing.JButton();
        btPtUmC = new javax.swing.JButton();
        btPtUmD = new javax.swing.JButton();
        btPtDica = new javax.swing.JButton();
        btPtVM = new javax.swing.JButton();
        btPtAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelPtUm.setPreferredSize(new java.awt.Dimension(700, 420));

        jlPtUmA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlPtUmA.setText("Qual é a vogal presente na");

        jlPtUmB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlPtUmB.setText("palavra \"CASA\"?");

        btPtUmA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtUmA.setText("A");
        btPtUmA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtUmAActionPerformed(evt);
            }
        });

        btPtUmB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtUmB.setText("C");
        btPtUmB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtUmBActionPerformed(evt);
            }
        });

        btPtUmC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtUmC.setText("S");
        btPtUmC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtUmCActionPerformed(evt);
            }
        });

        btPtUmD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPtUmD.setText("O");
        btPtUmD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtUmDActionPerformed(evt);
            }
        });

        btPtDica.setText("?");
        btPtDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtDicaActionPerformed(evt);
            }
        });

        btPtVM.setText("MENU");
        btPtVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtVMActionPerformed(evt);
            }
        });

        btPtAvancar.setText("Avançar");
        btPtAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPtUmLayout = new javax.swing.GroupLayout(PainelPtUm);
        PainelPtUm.setLayout(PainelPtUmLayout);
        PainelPtUmLayout.setHorizontalGroup(
            PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPtUmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPtUmB, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(PainelPtUmLayout.createSequentialGroup()
                .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelPtUmLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPtUmC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPtUmA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPtUmB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPtUmD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelPtUmLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btPtVM)
                        .addGap(50, 50, 50)
                        .addComponent(jlPtUmA)))
                .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPtUmLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(btPtDica)
                        .addContainerGap())
                    .addGroup(PainelPtUmLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btPtAvancar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PainelPtUmLayout.setVerticalGroup(
            PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPtUmLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPtUmA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPtDica)
                    .addComponent(btPtVM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPtUmB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPtUmA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPtUmB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPtUmLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PainelPtUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btPtUmC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPtUmD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPtUmLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPtAvancar)
                        .addGap(26, 26, 26))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(PainelPtUm, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPtUmAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtUmAActionPerformed
         
        pontosPt=pontosPt+20;
         System.out.println(""+pontosPt);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            stm.executeUpdate("INSERT into jogos (q1,q2,q3,q4,q5,q6,q7,q8,q9,q10) values ("+pontosPt+","+0+","+0+","+0+","+0+","+0+","+0+","+0+","+0+","+0+")");
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }   
   
        TelaPtDois.setVisible(true);
      dispose();
    }//GEN-LAST:event_btPtUmAActionPerformed

    private void btPtDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtDicaActionPerformed
      JOptionPane.showMessageDialog(null,"As vogais são A, E, I, O, U");
    }//GEN-LAST:event_btPtDicaActionPerformed

    private void btPtVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtVMActionPerformed
        new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btPtVMActionPerformed

    private void btPtAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtAvancarActionPerformed
        pontosPt=0;
        TelaPtDois.setVisible(true);
        dispose();
    }//GEN-LAST:event_btPtAvancarActionPerformed

    private void btPtUmBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtUmBActionPerformed
     pontosPt=pontosPt-5;   // TODO add your handling code here:
    }//GEN-LAST:event_btPtUmBActionPerformed

    private void btPtUmDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtUmDActionPerformed
    pontosPt=pontosPt-5;    // TODO add your handling code here:
    }//GEN-LAST:event_btPtUmDActionPerformed

    private void btPtUmCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtUmCActionPerformed
      pontosPt=pontosPt-5;  // TODO add your handling code here:
    }//GEN-LAST:event_btPtUmCActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPtUm;
    private javax.swing.JButton btPtAvancar;
    private javax.swing.JButton btPtDica;
    private javax.swing.JButton btPtUmA;
    private javax.swing.JButton btPtUmB;
    private javax.swing.JButton btPtUmC;
    private javax.swing.JButton btPtUmD;
    private javax.swing.JButton btPtVM;
    private javax.swing.JButton btVoltarMt;
    private javax.swing.JButton btVoltarMt1;
    private javax.swing.JLabel jlPtUmA;
    private javax.swing.JLabel jlPtUmB;
    // End of variables declaration//GEN-END:variables
}
