/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;

import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;
/**
 *
 * @author fellr
 */
public class QACinco extends javax.swing.JFrame {
    private QASeis TelaQASeis;
int pontosQA = PontosAluno.getPontosQA();
      int idAluno=0;
    /**
     * Creates new form QACinco
     */
    public QACinco() {
        initComponents();
        TelaQASeis = new QASeis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelQACinco = new javax.swing.JPanel();
        jlQACincoA = new javax.swing.JLabel();
        jlQACincoB = new javax.swing.JLabel();
        btQACincoA = new javax.swing.JButton();
        btQACincoB = new javax.swing.JButton();
        btQACincoC = new javax.swing.JButton();
        btQACincoD = new javax.swing.JButton();
        btQECincoMenu = new javax.swing.JButton();
        btAvancarQA = new javax.swing.JButton();
        btVoltarQA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlQACincoA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQACincoA.setText("Qual animal é conhecido como");

        jlQACincoB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQACincoB.setText("o rei da selva?");

        btQACincoA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoA.setText("CACHORRO");
        btQACincoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQACincoAActionPerformed(evt);
            }
        });

        btQACincoB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoB.setText("MACACO");
        btQACincoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQACincoBActionPerformed(evt);
            }
        });

        btQACincoC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoC.setText("LEOPARDO");
        btQACincoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQACincoCActionPerformed(evt);
            }
        });

        btQACincoD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoD.setText("LEÃO");
        btQACincoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQACincoDActionPerformed(evt);
            }
        });

        btQECincoMenu.setText("MENU");
        btQECincoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQECincoMenuActionPerformed(evt);
            }
        });

        btAvancarQA.setText("AVANÇAR");
        btAvancarQA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarQAActionPerformed(evt);
            }
        });

        btVoltarQA.setText("Voltar");
        btVoltarQA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarQAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelQACincoLayout = new javax.swing.GroupLayout(PainelQACinco);
        PainelQACinco.setLayout(PainelQACincoLayout);
        PainelQACincoLayout.setHorizontalGroup(
            PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQACincoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                        .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btQACincoA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                                .addComponent(btVoltarQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btQACincoC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82)
                        .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btQACincoB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQACincoD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(btAvancarQA)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                        .addGap(0, 105, Short.MAX_VALUE)
                        .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                                .addComponent(jlQACincoB)
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                                .addComponent(jlQACincoA)
                                .addGap(92, 92, 92))))
                    .addGroup(PainelQACincoLayout.createSequentialGroup()
                        .addComponent(btQECincoMenu)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelQACincoLayout.setVerticalGroup(
            PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQACincoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btQECincoMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlQACincoA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlQACincoB)
                .addGap(24, 24, 24)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQACincoA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQACincoB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQACincoC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQACincoD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAvancarQA)
                    .addComponent(btVoltarQA))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQACinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQACinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQACincoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQACincoDActionPerformed
      pontosQA=pontosQA+20;
        System.out.println(""+pontosQA);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                 
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q5="+pontosQA+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }   
        TelaQASeis.setVisible(true);
      dispose();
    }//GEN-LAST:event_btQACincoDActionPerformed

    private void btQACincoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQACincoAActionPerformed
     pontosQA=pontosQA-5;       // TODO add your handling code here:
    }//GEN-LAST:event_btQACincoAActionPerformed

    private void btQACincoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQACincoBActionPerformed
     pontosQA=pontosQA-5;       // TODO add your handling code here:
    }//GEN-LAST:event_btQACincoBActionPerformed

    private void btQACincoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQACincoCActionPerformed
       pontosQA=pontosQA-5;     // TODO add your handling code here:
    }//GEN-LAST:event_btQACincoCActionPerformed

    private void btQECincoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQECincoMenuActionPerformed
        new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btQECincoMenuActionPerformed

    private void btAvancarQAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarQAActionPerformed
        TelaQASeis.setVisible(true);
      dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btAvancarQAActionPerformed

    private void btVoltarQAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarQAActionPerformed
        new QAQuatro().show();
        dispose();
    }//GEN-LAST:event_btVoltarQAActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelQACinco;
    private javax.swing.JButton btAvancarQA;
    private javax.swing.JButton btQACincoA;
    private javax.swing.JButton btQACincoB;
    private javax.swing.JButton btQACincoC;
    private javax.swing.JButton btQACincoD;
    private javax.swing.JButton btQECincoMenu;
    private javax.swing.JButton btVoltarQA;
    private javax.swing.JLabel jlQACincoA;
    private javax.swing.JLabel jlQACincoB;
    // End of variables declaration//GEN-END:variables
}
