/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;

/**
 *
 * @author fellr
 */
public class QACinco extends javax.swing.JFrame {
    private QASeis TelaQASeis;

    /**
     * Creates new form QACinco
     */
    public QACinco() {
        initComponents();
        TelaQASeis = new QASeis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelQACinco = new javax.swing.JPanel();
        jlQACincoA = new javax.swing.JLabel();
        jlQACincoB = new javax.swing.JLabel();
        btQACincoA = new javax.swing.JButton();
        btQACincoB = new javax.swing.JButton();
        btQACincoC = new javax.swing.JButton();
        btQACincoD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlQACincoA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQACincoA.setText("Qual animal é conhecido como");

        jlQACincoB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQACincoB.setText("o rei da selva?");

        btQACincoA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoA.setText("CACHORRO");

        btQACincoB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoB.setText("MACACO");

        btQACincoC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoC.setText("LEOPARDO");

        btQACincoD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQACincoD.setText("LEÃO");
        btQACincoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQACincoDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelQACincoLayout = new javax.swing.GroupLayout(PainelQACinco);
        PainelQACinco.setLayout(PainelQACincoLayout);
        PainelQACincoLayout.setHorizontalGroup(
            PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btQACincoC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQACincoA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btQACincoB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQACincoD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                        .addComponent(jlQACincoB)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQACincoLayout.createSequentialGroup()
                        .addComponent(jlQACincoA)
                        .addGap(92, 92, 92))))
        );
        PainelQACincoLayout.setVerticalGroup(
            PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQACincoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jlQACincoA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlQACincoB)
                .addGap(24, 24, 24)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQACincoA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQACincoB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelQACincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQACincoC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQACincoD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQACinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQACinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQACincoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQACincoDActionPerformed
      TelaQASeis.setVisible(true);
      dispose();
    }//GEN-LAST:event_btQACincoDActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelQACinco;
    private javax.swing.JButton btQACincoA;
    private javax.swing.JButton btQACincoB;
    private javax.swing.JButton btQACincoC;
    private javax.swing.JButton btQACincoD;
    private javax.swing.JLabel jlQACincoA;
    private javax.swing.JLabel jlQACincoB;
    // End of variables declaration//GEN-END:variables
}
