/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;

/**
 *
 * @author fellr
 */
public class QADez extends javax.swing.JFrame {

    /**
     * Creates new form QADez
     */
    public QADez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelQADez = new javax.swing.JPanel();
        jlQADezA = new javax.swing.JLabel();
        jlQADezB = new javax.swing.JLabel();
        btQADezA = new javax.swing.JButton();
        btQADezB = new javax.swing.JButton();
        btQADezC = new javax.swing.JButton();
        btQADezD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlQADezA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQADezA.setText("Qual dos animais à seguir vive");

        jlQADezB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQADezB.setText("na agua?");

        btQADezA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQADezA.setText("LAGARTO");

        btQADezB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQADezB.setText("PEIXE");
        btQADezB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQADezBActionPerformed(evt);
            }
        });

        btQADezC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQADezC.setText("CANGURU");

        btQADezD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQADezD.setText("CABRA");

        javax.swing.GroupLayout PainelQADezLayout = new javax.swing.GroupLayout(PainelQADez);
        PainelQADez.setLayout(PainelQADezLayout);
        PainelQADezLayout.setHorizontalGroup(
            PainelQADezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQADezLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelQADezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQADezLayout.createSequentialGroup()
                        .addGroup(PainelQADezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btQADezA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQADezC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(PainelQADezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btQADezD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQADezB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQADezLayout.createSequentialGroup()
                        .addComponent(jlQADezB)
                        .addGap(276, 276, 276))))
            .addGroup(PainelQADezLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jlQADezA)
                .addGap(0, 114, Short.MAX_VALUE))
        );
        PainelQADezLayout.setVerticalGroup(
            PainelQADezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQADezLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlQADezA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlQADezB)
                .addGap(31, 31, 31)
                .addGroup(PainelQADezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQADezA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQADezB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelQADezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQADezC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQADezD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQADez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQADez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQADezBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQADezBActionPerformed
   
    }//GEN-LAST:event_btQADezBActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelQADez;
    private javax.swing.JButton btQADezA;
    private javax.swing.JButton btQADezB;
    private javax.swing.JButton btQADezC;
    private javax.swing.JButton btQADezD;
    private javax.swing.JLabel jlQADezA;
    private javax.swing.JLabel jlQADezB;
    // End of variables declaration//GEN-END:variables
}
