/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;

/**
 *
 * @author fellr
 */
public class QATres extends javax.swing.JFrame {
    private QAQuatro TelaQAQuatro;

    /**
     * Creates new form QATres
     */
    public QATres() {
        initComponents();
        TelaQAQuatro = new QAQuatro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelQATres = new javax.swing.JPanel();
        jlQATresA = new javax.swing.JLabel();
        jlQATresB = new javax.swing.JLabel();
        btQATresA = new javax.swing.JButton();
        btQATresB = new javax.swing.JButton();
        btQATresC = new javax.swing.JButton();
        btQATresD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlQATresA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQATresA.setText("Qual animal é conhecido por ter ");

        jlQATresB.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQATresB.setText("listras PRETAS e BRANCAS?");

        btQATresA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQATresA.setText("ZEBRA");
        btQATresA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQATresAActionPerformed(evt);
            }
        });

        btQATresB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQATresB.setText("GIRAFA");
        btQATresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQATresBActionPerformed(evt);
            }
        });

        btQATresC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQATresC.setText("TIGRE");
        btQATresC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQATresCActionPerformed(evt);
            }
        });

        btQATresD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQATresD.setText("AVESTRUZ");

        javax.swing.GroupLayout PainelQATresLayout = new javax.swing.GroupLayout(PainelQATres);
        PainelQATres.setLayout(PainelQATresLayout);
        PainelQATresLayout.setHorizontalGroup(
            PainelQATresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQATresLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jlQATresA)
                .addGap(90, 90, 90))
            .addGroup(PainelQATresLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(PainelQATresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlQATresB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelQATresLayout.createSequentialGroup()
                        .addGroup(PainelQATresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btQATresA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQATresC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(PainelQATresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btQATresD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQATresB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelQATresLayout.setVerticalGroup(
            PainelQATresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQATresLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jlQATresA)
                .addGap(18, 18, 18)
                .addComponent(jlQATresB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(PainelQATresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQATresB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQATresA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelQATresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQATresD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQATresC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQATres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQATres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQATresCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQATresCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btQATresCActionPerformed

    private void btQATresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQATresBActionPerformed
      
    }//GEN-LAST:event_btQATresBActionPerformed

    private void btQATresAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQATresAActionPerformed
      TelaQAQuatro.setVisible(true);
      dispose();
    }//GEN-LAST:event_btQATresAActionPerformed

    /**
     * @param args the cjlQATresline arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelQATres;
    private javax.swing.JButton btQATresA;
    private javax.swing.JButton btQATresB;
    private javax.swing.JButton btQATresC;
    private javax.swing.JButton btQATresD;
    private javax.swing.JLabel jlQATresA;
    private javax.swing.JLabel jlQATresB;
    // End of variables declaration//GEN-END:variables
}
