/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogos;

import dados.PontosAluno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import telas.menuPrincipal;

/**
 *
 * @author fellr
 */
public class QEQuatro extends javax.swing.JFrame {
    private QECinco TelaQECinco;
     int pontosQE = PontosAluno.getPontosQE();
      int idAluno=0;

    /**
     * Creates new form QEQuatro
     */
    public QEQuatro() {
        initComponents();
        TelaQECinco = new QECinco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelQEQuatro = new javax.swing.JPanel();
        jlQEQuatroA = new javax.swing.JLabel();
        btQEQuatroA = new javax.swing.JButton();
        btQEQuatroB = new javax.swing.JButton();
        btQEQuatroC = new javax.swing.JButton();
        btQEQuatroD = new javax.swing.JButton();
        btAvancarQE = new javax.swing.JButton();
        btQEQuatroMenu = new javax.swing.JButton();
        btVoltarMt = new javax.swing.JButton();
        btPtDica2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlQEQuatroA.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlQEQuatroA.setText("Qual é a cor da raposa?");

        btQEQuatroA.setBackground(new java.awt.Color(0, 0, 0));
        btQEQuatroA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQEQuatroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQEQuatroAActionPerformed(evt);
            }
        });

        btQEQuatroB.setBackground(new java.awt.Color(102, 153, 0));
        btQEQuatroB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQEQuatroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQEQuatroBActionPerformed(evt);
            }
        });

        btQEQuatroC.setBackground(new java.awt.Color(204, 102, 0));
        btQEQuatroC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQEQuatroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQEQuatroCActionPerformed(evt);
            }
        });

        btQEQuatroD.setBackground(new java.awt.Color(0, 102, 102));
        btQEQuatroD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btQEQuatroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQEQuatroDActionPerformed(evt);
            }
        });

        btAvancarQE.setText("AVANÇAR");
        btAvancarQE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarQEActionPerformed(evt);
            }
        });

        btQEQuatroMenu.setText("MENU");
        btQEQuatroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQEQuatroMenuActionPerformed(evt);
            }
        });

        btVoltarMt.setText("Voltar");
        btVoltarMt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMtActionPerformed(evt);
            }
        });

        btPtDica2.setText("?");
        btPtDica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPtDica2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelQEQuatroLayout = new javax.swing.GroupLayout(PainelQEQuatro);
        PainelQEQuatro.setLayout(PainelQEQuatroLayout);
        PainelQEQuatroLayout.setHorizontalGroup(
            PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQEQuatroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelQEQuatroLayout.createSequentialGroup()
                        .addGap(0, 127, Short.MAX_VALUE)
                        .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                                .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PainelQEQuatroLayout.createSequentialGroup()
                                        .addComponent(btQEQuatroC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btQEQuatroD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelQEQuatroLayout.createSequentialGroup()
                                        .addComponent(btQEQuatroA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(btQEQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(134, 134, 134))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                                .addComponent(jlQEQuatroA)
                                .addGap(162, 162, 162))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                        .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                                .addComponent(btVoltarMt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAvancarQE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                                .addComponent(btQEQuatroMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btPtDica2)))
                        .addContainerGap())))
        );
        PainelQEQuatroLayout.setVerticalGroup(
            PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPtDica2)
                    .addComponent(btQEQuatroMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                        .addComponent(jlQEQuatroA)
                        .addGap(40, 40, 40)
                        .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btQEQuatroA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQEQuatroB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btQEQuatroC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQEQuatroD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQEQuatroLayout.createSequentialGroup()
                        .addGroup(PainelQEQuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btVoltarMt)
                            .addComponent(btAvancarQE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQEQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelQEQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQEQuatroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQEQuatroCActionPerformed
      
        pontosQE=pontosQE+20;
        System.out.println(""+pontosQE);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aplicativo_educacional","root","");
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT * from jogos");
            while(res.next())
            {
                 
                idAluno= res.getInt("idAluno");
            }
            stm.executeUpdate("UPDATE jogos set q4="+pontosQE+" WHERE idAluno="+idAluno);
          
        }
                catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
            }
        TelaQECinco.setVisible(true);
      dispose();
    }//GEN-LAST:event_btQEQuatroCActionPerformed

    private void btQEQuatroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQEQuatroDActionPerformed
   pontosQE=pontosQE-5;      // TODO add your handling code here:
    }//GEN-LAST:event_btQEQuatroDActionPerformed

    private void btQEQuatroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQEQuatroAActionPerformed
   pontosQE=pontosQE-5;      // TODO add your handling code here:
    }//GEN-LAST:event_btQEQuatroAActionPerformed

    private void btQEQuatroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQEQuatroBActionPerformed
    pontosQE=pontosQE-5;     // TODO add your handling code here:
    }//GEN-LAST:event_btQEQuatroBActionPerformed

    private void btQEQuatroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQEQuatroMenuActionPerformed
        new menuPrincipal().show();
        dispose();
    }//GEN-LAST:event_btQEQuatroMenuActionPerformed

    private void btAvancarQEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarQEActionPerformed
     TelaQECinco.setVisible(true);
      dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btAvancarQEActionPerformed

    private void btVoltarMtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMtActionPerformed
        new QETres().show();
        dispose();
    }//GEN-LAST:event_btVoltarMtActionPerformed

    private void btPtDica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPtDica2ActionPerformed
        JOptionPane.showMessageDialog(null,"Geralmente em determinados dias do ano, o pôr do sol é da mesma cor!");
    }//GEN-LAST:event_btPtDica2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelQEQuatro;
    private javax.swing.JButton btAvancarQE;
    private javax.swing.JButton btPtDica2;
    private javax.swing.JButton btQEQuatroA;
    private javax.swing.JButton btQEQuatroB;
    private javax.swing.JButton btQEQuatroC;
    private javax.swing.JButton btQEQuatroD;
    private javax.swing.JButton btQEQuatroMenu;
    private javax.swing.JButton btVoltarMt;
    private javax.swing.JLabel jlQEQuatroA;
    // End of variables declaration//GEN-END:variables
}
